// <auto-generated />
using Audi.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Audi.DAL.Migrations
{
    [DbContext(typeof(AudiContext))]
    [Migration("20221021122928_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Audi.DAL.Models.AudiModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Brand")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Description")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Model")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Audi");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Audi",
                            Description = "The most luxary model",
                            Model = "A8l",
                            Price = 1090321
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Audi",
                            Description = " The most faster jeep",
                            Model = "RS Q8",
                            Price = 1090321
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Audi",
                            Description = "Sooo beautiful))",
                            Model = "RS7",
                            Price = 1090321
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
